CREATE TABLE [Talksoft].[Appointment_History]
(
	[Id]										INT IDENTITY(1,1),
	[Client_Id]									VARCHAR(50)	NULL,
	[Client_Id_Type]							VARCHAR(50)	NULL,
	[Talksoft_ClientId]							VARCHAR(50)	NULL,
	[Source_Appointment_Id]						VARCHAR(50) NULL,
	[Appointment_Holder_Id]          			VARCHAR(50)	NULL,
	[Appointment_Holder_Type]					VARCHAR(25) NULL,               	
	[Appointment_Holder_Name]					VARCHAR(50)	NULL,
	[Appointment_Holder_First_Name]				VARCHAR(50)	NULL,
	[Appointment_Holder_Last_Name]				VARCHAR(50)	NULL,
	[Appointment_Holder_Date_Time]				DATETIME	NULL,
	[Appointment_Holder_Home_Phone_Number]		BIGINT		NULL,
	[Appointment_Holder_Cell_Phone_Number]		BIGINT		NULL,
	[Appointment_Holder_Work_Phone_Number]		BIGINT		NULL,
	[Appointment_Holder_Email_Address]			VARCHAR(255)NULL,
	[Appointment_Type_Description]				VARCHAR(50)	NULL,
	[Appointment_Provider_Name]					VARCHAR(50)	NULL,
	[Location_Name]								VARCHAR(50)	NULL,
	[Language_Preferences]						VARCHAR(50)	NULL,
	[Appointment_Provider_Id]					VARCHAR(50)	NULL,
	[Location_Id]								VARCHAR(50)	NULL,
	[Appointment_Type_Id]						VARCHAR(50)	NULL,
	[Appointment_Holder_Preferred_Phone_Number]	VARCHAR(15)	NULL,
	[Resource_Name]								VARCHAR(15)	NULL,
	[Resource_Id]								VARCHAR(15)	NULL,
	[Sub_Account]								VARCHAR(15)	NULL,
	[Product_Id]								VARCHAR(15)	NULL,
	[Appointment_Holder_Phone_Allowed]			VARCHAR(1)	NULL,
	[Appointment_Holder_Text_Allowed]			VARCHAR(1)	NULL,
	[Appointment_Holder_Email_Allowed]			VARCHAR(1)	NULL,
	[Appointment_Holder_Preffered_Mode]			VARCHAR(15)	NULL,
	[TimeZone_Id]								VARCHAR(15)	NULL,
	[TimeZone_Name]								VARCHAR(15)	NULL,
	[Appointment_Status]						VARCHAR(25)	NULL,
	[DateTime_Appointment_Created]				DATETIME	NULL,
	[Batch_Id]									INT			NULL,
	[Status]									VARCHAR(15)	NULL,
	[File_Name]									VARCHAR(400)NULL,
	[Create_Date]								DATETIME	NULL,
	[Created_By]								VARCHAR(50)	NULL,
	[Update_Date]								DATETIME	NULL,
	[Updated_By]								VARCHAR(50)	NULL
)
